### PR TITLE
Add the entire Navy Seals copypasta in Russian

### PR DESCRIPTION
**Pull request by flexagoon**
For whatever reason I rate all online translator apps based on how well they can translate Navy Seals into Russian, and LibreTranslate/Argos was the worst one. This PR will probably solve this. I don't know why I decided to do this.

### CODE REVIEW

**Comment by PJ-Finlay** [comment]
Interesting choice thanks!

**Comment by flexagoon** [comment]
By the way, @PJ-Finlay, is the data from this repository currently used somewhere or at least is planned to be used in the near future?

**Comment by PJ-Finlay** [comment]
Not currently. Gathering user data is still a work in progress: https://github.com/LibreTranslate/LibreTranslate/pull/151

**Comment by flexagoon** [comment]
@PJ-Finlay got it. Also, AFAIK current models are trained on WikiMatrix from OPUS. Maybe you can consider also adding XL models which are trained om CCMatrix? It's like 15 times bigger then WIkiMatrix is

**Comment by PJ-Finlay** [comment]
I generally used CCMatrix too, for most models I used top few largest datasets on OPUS.

**Pull request merged**
